require("arthur.plugins-setup")
require("arthur.core.options")
require("arthur.core.keymaps")
require("arthur.core.colorscheme")
require("arthur.plugins.comment")
require("arthur.plugins.nvim-tree")
require("arthur.plugins.lualine")
